### ISSUE TITLE
404 for speedrun.com category links

### ISSUE THREAD

**Issue by robin-thoene** [CapitaineToinon/SpeedSouls#50]
### Summary

The category links to speedrun.com on the page https://speedsouls.com/submit are not correct all the time.

### Reproduce

Steps:

1. Open [submit a run page](https://speedsouls.com/submit)
2. Open for example Dark Souls III
3. Click on the category "Any%"

Result:

![image](https://github.com/CapitaineToinon/SpeedSouls/assets/110201991/f8db2fb1-fa61-4fce-886b-c4d0d2e1fe43)

**Comment by robin-thoene** [comment]
I have no vue.js experience yet, but I worked with react very regularly during the last 3 and a half years.

I am a Fromsoft and speedrunning fan and would love to contribute to the ecosystem you and other developers created around these games.

So if it is okay for you I would like to try fixing this issue by myself.

**Comment by CapitaineToinon** [comment]
Because of internal problems within the community, this website has been disabled and this issue will therefore not be fixed. Thank you very much for your help, this is just unfortunate timing and nothing on your hand.
